"""Add supplier_id to products table

Revision ID: 06e8a1f5d25f
Revises: 84f1e4a30b5e
Create Date: 2025-11-17 08:14:13.851935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e8a1f5d25f'
down_revision: Union[str, Sequence[str], None] = '84f1e4a30b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('pos_x', sa.Integer(), nullable=False),
    sa.Column('pos_y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('rotation', sa.Integer(), nullable=False),
    sa.Column('wall_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_walls_id'), 'walls', ['id'], unique=False)
    op.add_column('products', sa.Column('cost_price', sa.Float(), nullable=True))
    op.execute("CREATE TYPE producttype AS ENUM ('SIMPLE', 'COMPOSED', 'VARIATION')")
    op.add_column('products', sa.Column('product_type', sa.Enum('SIMPLE', 'COMPOSED', 'VARIATION', name='producttype'), server_default='SIMPLE', nullable=False))
    op.add_column('products', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'supplier_id')
    op.drop_column('products', 'product_type')
    op.drop_column('products', 'cost_price')
    op.drop_index(op.f('ix_walls_id'), table_name='walls')
    op.drop_table('walls')
    op.execute("DROP TYPE producttype")
    # ### end Alembic commands ###
