"""Add campaigns table

Revision ID: 9573a4cf8a7f
Revises: 06e8a1f5d25f
Create Date: 2025-11-19 09:40:28.072017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9573a4cf8a7f'
down_revision: Union[str, Sequence[str], None] = '06e8a1f5d25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
