"""create_feedbacks_table_image

Revision ID: c89cc8349e10
Revises: fc7883fb14cd
Create Date: 2026-05-28 09:36:23.771371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89cc8349e10'
down_revision: Union[str, Sequence[str], None] = 'fc7883fb14cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('image_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'image_data')
    # ### end Alembic commands ###
